package pack1;


public class ExceptionDemo {
 //one try can follow by multiple catch blocks
 //catch should be an immediate block after try
	
	
	
	
	public static void main(String[] args) {
		// TODO Auto-generated method stub
		int b=7;
		int c=0;
	try {
		int k=b/c;
		System.out.println(k);
	} catch (Exception e) {
		System.out.println("i catched the error");
		// TODO: handle exception
	}	
	
	
		
		
	
	
	

		
		}
	}


